export const CollectionElement = {
	remote: null,
	content: {
		url:
			"https://mv-repo.schul-cloud.org/edu-sharing/components/render/311a8e89-6352-4050-968a-026e465a3b99",
		hash: null,
		version: "1.0",
	},
	license: {
		icon:
			"https://mv-repo.schul-cloud.org/edu-sharing/ccimages/licenses/copyright-free.svg",
		url: null,
	},
	isDirectory: false,
	commentCount: 0,
	rating: null,
	ref: {
		repo: "mv-repo.schul-cloud.org",
		id: "311a8e89-6352-4050-968a-026e465a3b99",
		archived: false,
		isHomeRepo: true,
	},
	parent: {
		repo: "mv-repo.schul-cloud.org",
		id: "9bdf97e0-be67-4c7e-a435-08ff25723dc4",
		archived: false,
		isHomeRepo: true,
	},
	type: "ccm:io",
	aspects: [
		"cclom:lifecycle",
		"cclom:technical",
		"ccm:permission_history",
		"ccm:eduscope",
		"ccm:iometadata",
		"cm:versionable",
		"ccm:usageaspect",
		"sys:referenceable",
		"sys:localized",
		"cclom:schema",
		"ccm:basemetadata",
		"cm:metadataset",
		"ccm:licenses",
		"ccm:commonlicenses",
		"cclom:rights",
		"cm:thumbnailed",
		"cclom:meta-metadata",
		"cm:auditable",
		"ccm:lomreplication",
		"cclom:general",
		"ccm:hpi",
		"ccm:educontext",
	],
	name: "mock data",
	title: "mock data",
	metadataset: "mds_oeh",
	repositoryType: "ALFRESCO",
	createdAt: "2021-01-06T16:58:36Z",
	createdBy: {
		profile: null,
		firstName: "Administrator",
		lastName: "Edu-Sharing",
		mailbox: "mock",
	},
	modifiedAt: "2021-01-11T16:35:28Z",
	modifiedBy: {
		profile: null,
		firstName: "Administrator",
		lastName: "Edu-Sharing",
		mailbox: "mock",
	},
	access: [
		"Read",
		"ReadAll",
		"Comment",
		"Feedback",
		"AddChildren",
		"ChangePermissions",
		"Write",
		"Delete",
		"CCPublish",
	],
	downloadUrl:
		"https://mv-repo.schul-cloud.org/edu-sharing/eduservlet/download?nodeId=311a8e89-6352-4050-968a-0521465a3b99",
	properties: {
		"ccm:replicationsourcehash": ["-2176748420977789431"],
		"ccm:original": ["311a8e89-6352-4050-968a-026e465a3b99"],
		"ccm:ph_modified": ["1609952316858"],
		"cm:created": ["1609952316352"],
		"virtual:commentcount": ["0"],
		"cclom:version": ["1.0"],
		"virtual:licenseicon": [
			"https://mv-repo.schul-cloud.org/edu-sharing/ccimages/licenses/copyright-free.svg",
		],
		"virtual:usagecount": ["0"],
		"ccm:objecttype": ["MATERIAL"],
		"sys:node-uuid": ["311a8e89-6352-4050-968a-026e465a3b99"],
		"ccm:replicationsource": ["mediothek_pixiothek_spider"],
		"ccm:hpi_lom_relation": [
			"{'kind': 'ispartof', 'resource': {'identifier': ['96128580-e470-5eb7-bc6c-3045bdb1fe46']}}",
		],
		"virtual:childobjectcount": ["0"],
		"ccm:replicationsourceuuid": ["d2ae40e0-d5e8-5139-b28e-0855c405d91d"],
		"cclom:title": ["# 3 - Mock (19:05min) (mp4)"],
		"ccm:ph_modifiedISO8601": ["2021-01-06T16:58:36.858Z"],
		"sys:store-protocol": ["workspace"],
		"sys:store-identifier": ["SpacesStore"],
		"ccm:version_comment": ["PREVIEW_CHANGED"],
		"ccm:create_version": ["false"],
		"ccm:hpi_lom_general_aggregationlevel": ["1"],
		"cm:modifiedISO8601": ["2021-01-11T16:35:28.384Z"],
		"sys:node-dbid": ["3660611"],
		"ccm:wwwurl": [
			"https://www.schulportal-thueringen.de/tip/resources/medien/49053?dateiname=#3 - mock.mp4",
		],
		"cm:edu_metadataset": ["mds_oeh"],
		"ccm:objecttype_DISPLAYNAME": ["Material"],
		"cm:creator": ["admin"],
		"cm:autoVersion": ["false"],
		"virtual:permalink": [
			"https://mv-repo.schul-cloud.org/edu-sharing/components/render/311a8e89-6352-4050-968a-0521465a3b99/1.0",
		],
		"cm:versionLabel": ["1.0"],
		"cm:versionable": ["true"],
		"cm:created_LONG": ["1609952316352"],
		"virtual:primaryparent_nodeid": ["9bdf97e0-be67-4c7e-a435-08gf25723dc4"],
		"ccm:replicationsourceid": ["49053"],
		"ccm:replicationsource_DISPLAYNAME": ["MediothekPixiothek"],
		"cm:createdISO8601": ["2021-01-06T16:58:36.352Z"],
		"ccm:ph_action": ["PERMISSION_ADD"],
		"cclom:general_description": ["LoremIpsum "],
		"cm:modified": ["1610382928384"],
		"cm:edu_forcemetadataset": ["true"],
		"cm:modifier": ["admin"],
		"cm:autoVersionOnUpdateProps": ["false"],
		"cclom:location": [
			"https://www.schulportal-thueringen.de/tip/resources/medien/49053?dateiname=#3 - mock.mp4",
		],
		"ccm:educontextname": ["default"],
		"ccm:ph_modified_LONG": ["1609952316858"],
		"ccm:hpi_searchable": ["0"],
		"cm:modified_LONG": ["1610382928384"],
		"cm:automaticUpdate": ["true"],
		"cm:name": ["# 3 - mock (19_05min) (mp4)_1610382926683"],
		"ccm:ph_invited": ["GROUP_Thuringia-public"],
		"ccm:ph_users": ["admin"],
		"ccm:ph_history": [
			'{"notifyUser":"admin","notifyAction":"PERMISSION_ADD","user":{"username":"admin","authorityName":"admin","authorityType":"USER"},"created":"Jan 6, 2021 5:58:36 PM","acl":{"inherited":true,"aces":[{"authority":"GROUP_Thuringia-public","permission":"CCPublish","accessStatus":"acepted","authorityType":"GROUP","group":{"name":"GROUP_Thuringia-public","repositoryId":"mv-repo.schul-cloud.org","nodeId":"a99c6b4a-5065-4ec3-8ea4-0470d8a7da89","editable":true,"authorityName":"GROUP_Thuringia-public","authorityType":"GROUP"},"id":0,"isInherited":false,"isEdited":false},{"authority":"GROUP_Thuringia-public","permission":"Consumer","accessStatus":"acepted","authorityType":"GROUP","group":{"name":"GROUP_Thuringia-public","repositoryId":"mv-repo.schul-cloud.org","nodeId":"a99c6b4a-5065-4ec3-8ea4-0470d8a7da89","editable":true,"authorityName":"GROUP_Thuringia-public","authorityType":"GROUP"},"id":0,"isInherited":false,"isEdited":false}]}}',
		],
		"cm:initialVersion": ["false"],
		"cclom:general_keyword": [
			"Krisenzeit",
			"Krise",
			"Schulleitungen",
			"FKE",
			"Führungskräfteentwicklung",
			"Schulleitung",
			"Corona",
		],
		"ccm:commonlicense_key": ["COPYRIGHT_FREE"],
	},
	mimetype: null,
	mediatype: "link",
	size: null,
	preview: {
		isIcon: false,
		isGenerated: false,
		type: "TYPE_USERDEFINED",
		url:
			"https://mv-repo.schul-cloud.org/edu-sharing/preview?nodeId=ce34a2f3-d089-4a88-b615-2899959af60b&storeProtocol=workspace&storeId=SpacesStore&dontcache=1612375981028&crop=true&maxWidth=300&maxHeight=300",
		width: null,
		height: null,
	},
	iconURL:
		"https://mv-repo.schul-cloud.org/edu-sharing/themes/default/images/common/mime-types/svg/link.svg",
	collection: null,
	owner: {
		profile: null,
		firstName: "Administrator",
		lastName: "Edu-Sharing",
		mailbox: "mock",
	},
};
