export const Resource = {
	remote: null,
	content: {
		url: null,
		hash: null,
		version: "1.0",
	},
	license: {
		icon:
			"https://mv-repo.hpi-schul-cloud.de/edu-sharing/ccimages/licenses/none.svg",
		url: null,
	},
	isDirectory: false,
	commentCount: 0,
	rating: null,
	ref: {
		repo: "mv-repo.hpi-schul-cloud.de",
		id: "7f35e810-9a63-4e18-9331-b1bf4ab5fa06",
		archived: false,
		isHomeRepo: true,
	},
	parent: {
		repo: "mv-repo.hpi-schul-cloud.de",
		id: null,
		archived: false,
		isHomeRepo: true,
	},
	type: "ccm:io",
	aspects: [
		"cm:metadataset",
		"cclom:technical",
		"cm:versionable",
		"cclom:schema",
		"sys:localized",
		"cclom:general",
		"cclom:meta-metadata",
		"cm:titled",
		"ccm:commonlicenses",
		"cclom:lifecycle",
		"ccm:eduscope",
		"cclom:rights",
		"ccm:lomreplication",
		"ccm:licenses",
		"cm:thumbnailed",
		"ccm:basemetadata",
		"ccm:usageaspect",
		"sys:referenceable",
		"ccm:iometadata",
		"cm:auditable",
	],
	name: "Technik der Dotierung",
	title: "Technik der Dotierung",
	metadataset: "default",
	repositoryType: "ALFRESCO",
	createdAt: null,
	createdBy: {
		profile: null,
		firstName: null,
		lastName: null,
		mailbox: null,
	},
	modifiedAt: null,
	modifiedBy: {
		profile: null,
		firstName: null,
		lastName: null,
		mailbox: null,
	},
	access: [
		"Read",
		"ReadPreview",
		"ReadAll",
		"Comment",
		"Feedback",
		"AddChildren",
		"ReadPermissions",
		"ChangePermissions",
		"ReadChildren",
		"DeleteChildren",
		"Write",
		"Delete",
		"CCPublish",
	],
	downloadUrl: null,
	properties: {
		"cm:creator": ["admin"],
		"cm:autoVersion": ["false"],
		"ccm:original": ["7f35e810-9a63-4e18-9331-b1bf4ab5fa06"],
		"cclom:copyright_and_other_restrictions": ["true"],
		"cm:created": ["1580305426433"],
		"cm:versionLabel": ["1.0"],
		"cclom:aggregationlevel": ["1"],
		"ccm:replicationsourcetimestamp": ["2020-01-29T13:44:27Z"],
		"cclom:version": ["1.0"],
		"ccm:taxonentry": [
			"Elektronik; Einführung in die Elektronik; ; Grundwissen",
		],
		"cclom:general_language": ["[]"],
		"ccm:thumbnailurl": [
			"https://www.leifiphysik.de/sites/default/files/medien/leifi-physik-logo_0.jpg",
		],
		"sys:node-uuid": ["7f35e810-9a63-4e18-9331-b1bf4ab5fa06"],
		"ccm:lifecyclecontributer_publisher": [
			"\n                <![CDATA[BEGIN:VCARD\nFN:LEIFI Physik\nORG:LEIFI Physik\nN:LEIFI Physik\nVERSION:3.0\nEND:VCARD]]>\n            ",
		],
		"ccm:replicationsourceid": ["26138"],
		"ccm:replicationsource": ["LEIFI Physik"],
		"ccm:replicationsourceuuid": ["3b1a6547-9ae1-5663-9fad-ae76b472d056"],
		"ccm:metadatacontributer_provider": [
			"\n                LEIFI Physik\n            ",
		],
		"sys:locale": ["de_DE_"],
		"cclom:general_description": ["<ul><li>Lorem Ipsum</li></ul>"],
		"cm:modified": ["1580305426433"],
		"cclom:rights_description": [
			"Keine Angabe, es gilt die gesetzliche Regelung",
		],
		"cm:edu_forcemetadataset": ["false"],
		"ccm:taxonid": ["120"],
		"cm:title": ["Technik der Dotierung"],
		"cm:modifier": ["admin"],
		"cclom:status": ["final"],
		"cm:autoVersionOnUpdateProps": ["false"],
		"cclom:location": [
			"https://www.leifiphysik.de/elektronik/einfuehrung-die-elektronik/technik-der-dotierung",
		],
		"ccm:educationalintendedenduserrole": ["[learner, teacher]"],
		"cclom:title": ["Technik der Dotierung"],
		"ccm:educationalcontext": [
			"[Baden-Württemberg; 9. Jahrgang, Baden-Württemberg; 10. Jahrgang, Baden-Württemberg; 12. Jahrgang, Bayern; 9. Jahrgang, Brandenburg; 9. Jahrgang, Brandenburg; 10. Jahrgang, Hessen; 11. Jahrgang, Niedersachsen; 9. Jahrgang, Niedersachsen; 10. Jahrgang, Rheinland-Pfalz; 10. Jahrgang, Rheinland-Pfalz; 13. Jahrgang, Saarland; 9. Jahrgang, Sachsen; 9. Jahrgang, Sachsen; 11. Jahrgang, Sachsen-Anhalt; 9. Jahrgang, Schleswig-Holstein; 12. Jahrgang, Schleswig-Holstein; 13. Jahrgang, Thüringen; 7. Jahrgang, Thüringen; 8. Jahrgang, Thüringen; 9. Jahrgang]",
		],
		"sys:store-protocol": ["workspace"],
		"sys:store-identifier": ["SpacesStore"],
		"cclom:structure": ["atomic"],
		"cclom:format": ["text/html"],
		"ccm:educationallearningresourcetype": ["web page"],
		"cm:automaticUpdate": ["true"],
		"cm:name": ["Technik der Dotierung"],
		"ccm:create_version": ["false"],
		"ccm:wwwurl": [
			"https://www.leifiphysik.de/elektronik/einfuehrung-die-elektronik/technik-der-dotierung",
		],
		"sys:node-dbid": ["6022"],
		"cm:initialVersion": ["false"],
		"cm:edu_metadataset": ["default"],
		"cclom:general_keyword": [
			"Elektronik; Einführung in die Elektronik; ; Grundwissen",
		],
	},
	mimetype: "text/html",
	mediatype: "file-script",
	size: null,
	preview: {
		isIcon: true,
		isGenerated: true,
		type: "TYPE_EXTERNAL",
		url:
			"https://mv-repo.hpi-schul-cloud.de/edu-sharing/preview?nodeId=ce34a2f3-d089-4a88-b615-2899959af60b&storeProtocol=workspace&storeId=SpacesStore&dontcache=1612375981028&crop=true&maxWidth=300&maxHeight=300",
		width: null,
		height: null,
	},
	iconURL:
		"https://mv-repo.hpi-schul-cloud.de/edu-sharing/themes/default/images/common/mime-types/svg/file-script.svg",
	collection: null,
	owner: {
		profile: null,
		firstName: "Administrator",
		lastName: "Edu-Sharing",
		mailbox: "admin@mv-repo.hpi-schul-cloud.de",
	},
};
