/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AccountByIdBodyParams } from '../models';
// @ts-ignore
import { AccountResponse } from '../models';
// @ts-ignore
import { AccountSearchListResponse } from '../models';
// @ts-ignore
import { EntityNotFoundError } from '../models';
// @ts-ignore
import { ForbiddenOperationError } from '../models';
// @ts-ignore
import { PatchMyAccountParams } from '../models';
// @ts-ignore
import { PatchMyPasswordParams } from '../models';
// @ts-ignore
import { ValidationError } from '../models';
/**
 * AccountApi - axios parameter creator
 * @export
 */
export const AccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccountById: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteAccountById', 'id', id)
            const localVarPath = `/account/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAccountById: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('findAccountById', 'id', id)
            const localVarPath = `/account/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates the the temporary account password for the authenticated user.
         * @param {PatchMyPasswordParams} patchMyPasswordParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceMyPassword: async (patchMyPasswordParams: PatchMyPasswordParams, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'patchMyPasswordParams' is not null or undefined
            assertParamExists('replaceMyPassword', 'patchMyPasswordParams', patchMyPasswordParams)
            const localVarPath = `/account/me/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchMyPasswordParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns all accounts which satisfies the given criteria. For unlimited access Superhero role is REQUIRED.
         * @param {'userId' | 'username'} type The search criteria.
         * @param {string} value The search value.
         * @param {number} [skip] Number of elements (not pages) to be skipped
         * @param {number} [limit] Page limit, defaults to 10.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAccounts: async (type: 'userId' | 'username', value: string, skip?: number, limit?: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('searchAccounts', 'type', type)
            // verify required parameter 'value' is not null or undefined
            assertParamExists('searchAccounts', 'value', value)
            const localVarPath = `/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (value !== undefined) {
                localVarQueryParameter['value'] = value;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {AccountByIdBodyParams} accountByIdBodyParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccountById: async (id: string, accountByIdBodyParams: AccountByIdBodyParams, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAccountById', 'id', id)
            // verify required parameter 'accountByIdBodyParams' is not null or undefined
            assertParamExists('updateAccountById', 'accountByIdBodyParams', accountByIdBodyParams)
            const localVarPath = `/account/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(accountByIdBodyParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates an account for the authenticated user.
         * @param {PatchMyAccountParams} patchMyAccountParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMyAccount: async (patchMyAccountParams: PatchMyAccountParams, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'patchMyAccountParams' is not null or undefined
            assertParamExists('updateMyAccount', 'patchMyAccountParams', patchMyAccountParams)
            const localVarPath = `/account/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchMyAccountParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountApi - functional programming interface
 * @export
 */
export const AccountApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Deletes an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAccountById(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAccountById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Returns an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAccountById(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findAccountById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Updates the the temporary account password for the authenticated user.
         * @param {PatchMyPasswordParams} patchMyPasswordParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async replaceMyPassword(patchMyPasswordParams: PatchMyPasswordParams, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.replaceMyPassword(patchMyPasswordParams, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Returns all accounts which satisfies the given criteria. For unlimited access Superhero role is REQUIRED.
         * @param {'userId' | 'username'} type The search criteria.
         * @param {string} value The search value.
         * @param {number} [skip] Number of elements (not pages) to be skipped
         * @param {number} [limit] Page limit, defaults to 10.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchAccounts(type: 'userId' | 'username', value: string, skip?: number, limit?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountSearchListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchAccounts(type, value, skip, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Updates an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {AccountByIdBodyParams} accountByIdBodyParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAccountById(id: string, accountByIdBodyParams: AccountByIdBodyParams, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAccountById(id, accountByIdBodyParams, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Updates an account for the authenticated user.
         * @param {PatchMyAccountParams} patchMyAccountParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMyAccount(patchMyAccountParams: PatchMyAccountParams, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMyAccount(patchMyAccountParams, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AccountApi - factory interface
 * @export
 */
export const AccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountApiFp(configuration)
    return {
        /**
         * 
         * @summary Deletes an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccountById(id: string, options?: any): AxiosPromise<AccountResponse> {
            return localVarFp.deleteAccountById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAccountById(id: string, options?: any): AxiosPromise<AccountResponse> {
            return localVarFp.findAccountById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates the the temporary account password for the authenticated user.
         * @param {PatchMyPasswordParams} patchMyPasswordParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceMyPassword(patchMyPasswordParams: PatchMyPasswordParams, options?: any): AxiosPromise<void> {
            return localVarFp.replaceMyPassword(patchMyPasswordParams, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns all accounts which satisfies the given criteria. For unlimited access Superhero role is REQUIRED.
         * @param {'userId' | 'username'} type The search criteria.
         * @param {string} value The search value.
         * @param {number} [skip] Number of elements (not pages) to be skipped
         * @param {number} [limit] Page limit, defaults to 10.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAccounts(type: 'userId' | 'username', value: string, skip?: number, limit?: number, options?: any): AxiosPromise<AccountSearchListResponse> {
            return localVarFp.searchAccounts(type, value, skip, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates an account with given id. Superhero role is REQUIRED.
         * @param {string} id The id for the account as MongoDB id.
         * @param {AccountByIdBodyParams} accountByIdBodyParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccountById(id: string, accountByIdBodyParams: AccountByIdBodyParams, options?: any): AxiosPromise<AccountResponse> {
            return localVarFp.updateAccountById(id, accountByIdBodyParams, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates an account for the authenticated user.
         * @param {PatchMyAccountParams} patchMyAccountParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMyAccount(patchMyAccountParams: PatchMyAccountParams, options?: any): AxiosPromise<void> {
            return localVarFp.updateMyAccount(patchMyAccountParams, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountApi - interface
 * @export
 * @interface AccountApi
 */
export interface AccountApiInterface {
    /**
     * 
     * @summary Deletes an account with given id. Superhero role is REQUIRED.
     * @param {string} id The id for the account as MongoDB id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    deleteAccountById(id: string, options?: any): AxiosPromise<AccountResponse>;

    /**
     * 
     * @summary Returns an account with given id. Superhero role is REQUIRED.
     * @param {string} id The id for the account as MongoDB id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    findAccountById(id: string, options?: any): AxiosPromise<AccountResponse>;

    /**
     * 
     * @summary Updates the the temporary account password for the authenticated user.
     * @param {PatchMyPasswordParams} patchMyPasswordParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    replaceMyPassword(patchMyPasswordParams: PatchMyPasswordParams, options?: any): AxiosPromise<void>;

    /**
     * 
     * @summary Returns all accounts which satisfies the given criteria. For unlimited access Superhero role is REQUIRED.
     * @param {'userId' | 'username'} type The search criteria.
     * @param {string} value The search value.
     * @param {number} [skip] Number of elements (not pages) to be skipped
     * @param {number} [limit] Page limit, defaults to 10.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    searchAccounts(type: 'userId' | 'username', value: string, skip?: number, limit?: number, options?: any): AxiosPromise<AccountSearchListResponse>;

    /**
     * 
     * @summary Updates an account with given id. Superhero role is REQUIRED.
     * @param {string} id The id for the account as MongoDB id.
     * @param {AccountByIdBodyParams} accountByIdBodyParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    updateAccountById(id: string, accountByIdBodyParams: AccountByIdBodyParams, options?: any): AxiosPromise<AccountResponse>;

    /**
     * 
     * @summary Updates an account for the authenticated user.
     * @param {PatchMyAccountParams} patchMyAccountParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    updateMyAccount(patchMyAccountParams: PatchMyAccountParams, options?: any): AxiosPromise<void>;

}

/**
 * AccountApi - object-oriented interface
 * @export
 * @class AccountApi
 * @extends {BaseAPI}
 */
export class AccountApi extends BaseAPI implements AccountApiInterface {
    /**
     * 
     * @summary Deletes an account with given id. Superhero role is REQUIRED.
     * @param {string} id The id for the account as MongoDB id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public deleteAccountById(id: string, options?: any) {
        return AccountApiFp(this.configuration).deleteAccountById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns an account with given id. Superhero role is REQUIRED.
     * @param {string} id The id for the account as MongoDB id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public findAccountById(id: string, options?: any) {
        return AccountApiFp(this.configuration).findAccountById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates the the temporary account password for the authenticated user.
     * @param {PatchMyPasswordParams} patchMyPasswordParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public replaceMyPassword(patchMyPasswordParams: PatchMyPasswordParams, options?: any) {
        return AccountApiFp(this.configuration).replaceMyPassword(patchMyPasswordParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns all accounts which satisfies the given criteria. For unlimited access Superhero role is REQUIRED.
     * @param {'userId' | 'username'} type The search criteria.
     * @param {string} value The search value.
     * @param {number} [skip] Number of elements (not pages) to be skipped
     * @param {number} [limit] Page limit, defaults to 10.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public searchAccounts(type: 'userId' | 'username', value: string, skip?: number, limit?: number, options?: any) {
        return AccountApiFp(this.configuration).searchAccounts(type, value, skip, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates an account with given id. Superhero role is REQUIRED.
     * @param {string} id The id for the account as MongoDB id.
     * @param {AccountByIdBodyParams} accountByIdBodyParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public updateAccountById(id: string, accountByIdBodyParams: AccountByIdBodyParams, options?: any) {
        return AccountApiFp(this.configuration).updateAccountById(id, accountByIdBodyParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates an account for the authenticated user.
     * @param {PatchMyAccountParams} patchMyAccountParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public updateMyAccount(patchMyAccountParams: PatchMyAccountParams, options?: any) {
        return AccountApiFp(this.configuration).updateMyAccount(patchMyAccountParams, options).then((request) => request(this.axios, this.basePath));
    }
}
