/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FileRecordParams } from './file-record-params';

/**
 * 
 * @export
 * @interface CopyFilesOfParentParams
 */
export interface CopyFilesOfParentParams {
    /**
     * 
     * @type {FileRecordParams}
     * @memberof CopyFilesOfParentParams
     */
    target: FileRecordParams;
}


