version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "01:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    labels:
      - dependencies
    versioning-strategy: increase
    ignore:
      - dependency-name: vue-svg-loader
        versions:
          - "> 0.16.0"
          - "< 0.17"
      - dependency-name: vue
        versions: ["3.x"]
      - dependency-name: nuxt
        versions: ["3.x"]
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 2
    rebase-strategy: disabled
  - package-ecosystem: docker
    directory: "/deploy"
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 2
    labels:
      - dependencies
    rebase-strategy: disabled
