version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 2
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: vue-svg-loader
    versions:
    - "> 0.16.0, < 0.17"
  - dependency-name: puppeteer
    versions:
    - 5.5.0
    - 8.0.0
  - dependency-name: jwt-decode
    versions:
    - 3.0.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.7
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
  - dependency-name: prettier
    versions:
    - 2.2.0
  - dependency-name: stylelint
    versions:
    - 13.9.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.8
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
  - dependency-name: "@testing-library/vue"
    versions:
    - 5.3.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@nuxt/types"
    versions:
    - 2.14.12
  - dependency-name: tiptap
    versions:
    - 1.31.0
  - dependency-name: faker
    versions:
    - 5.1.0
  - dependency-name: nuxt
    versions:
    - 2.14.9
  - dependency-name: vue-i18n
    versions:
    - 8.22.2
  - dependency-name: jest-image-snapshot
    versions:
    - 4.3.0
  - dependency-name: sharp
    versions:
    - 0.27.0
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 2
  rebase-strategy: disabled
- package-ecosystem: docker
  directory: "/deploy"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 2
  labels:
  - dependencies
  rebase-strategy: disabled
