default: true
# Rule customizations for markdownlint go here
# https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

# Disable line length restrictions, because editor soft-wrapping is being used
line-length: false
# allow hard tabs, look at the eslint config for more details
no-hard-tabs: false
# allow inline html
no-inline-html: false
# Prettier overrides
no-trailing-punctuation: false
no-multiple-blanks: false
list-marker-space: false
no-duplicate-heading: false
