pull_request_rules:
  #######################
  # MERGE PRECONDITIONS
  #######################
  - name: add WIP label when WIP is in title
    conditions:
      - title~=WIP
    actions:
      comment:
        message: Please remove WIP from the title. We have set the WIP Label for you instead.
      label:
        add:
          - WIP
  - name: remove "ready to merge" label when pull is not approved yet
    conditions:
      - -status-success~=pullapprove
      - label~=ready to merge
    actions:
      comment:
        message: The "ready to merge" label can only be set on approved pull request
      label:
        remove:
          - ready to merge
  - name: label PRs with conflicts
    conditions:
      - conflict
    actions:
      label:
        add:
          - has conflicts
  - name: remove has conflicts label if conflicts got resolved
    conditions:
      - label~=has conflicts
      - -conflict
    actions:
      label:
        remove:
          - has conflicts

  #######################
  # AUTO MERGING
  #######################
  - name: auto merge language file updates
    conditions:
      - author=schul-cloud-bot
      # PR must only contain language file changes
      - -files~=^(?!locale\/.*\.json)
    actions:
      merge:
        method: squash
        strict: true
  - name: auto merge passing Dependabot pull requests
    conditions:
      # match dependabot[bot] and dependabot-preview[bot]
      - author~=dependabot(-preview)?\[bot\]
      - label~=dependencies
    actions:
      merge:
        method: squash
        strict: true
  - name: auto merge when ready to merge label is set
    conditions:
      - label=ready to merge
    actions:
      merge:
        method: merge
        strict: true

  #######################
  # CLEANUP AFTER MERGE
  #######################
  - name: remove ready to merge when merged
    conditions:
      - merged
      - label=ready to merge
    actions:
      label:
        add:
          - auto_merged
        remove:
          - ready to merge
  - name: delete merged branches
    conditions:
      - merged
      - label!=WIP
    actions:
      delete_head_branch: {}
