version: 3

pullapprove_conditions:
  - condition: "'WIP' not in labels"
    unmet_status: pending
    explanation: "Work in progress"

  # not tested yet
  # - condition: "'*lint*' in statuses.succeeded"
  #   unmet_status: failure
  #   explanation: "Linter must pass before review starts"
  # - condition: "'*test*' in statuses.succeeded"
  #   unmet_status: failure
  #   explanation: "Linter must pass before review starts"

groups:
  ###############################
  # GENERAL REQUEST FOR REVIEW
  ###############################
  nuxt-core:
    conditions:
      # not created by a bot
      - "'schul-cloud-bot' not in author.username"
      - "'dependabot' not in author.username"
      - "'greenkeeper' not in author.username"
    reviews:
      required: 1 # 1 approval from this group is required
      request: 2 # 2 reviews requests will be sent at a time
      request_order: shuffle # reviewers will be chosen in a random order
    reviewers:
      teams:
        - VueCoreDevs
    labels:
      pending: "waiting for review"
  ###############################
  # LABEL SPECIFIC REQUESTS
  ###############################
  # integrathors:
  #   conditions:
  #     - "'IntegraTHORs' in labels"
  #   reviews:
  #     required: 1 # 1 approval from this group are required
  #     request: 2 # 2 reviews requests will be sent at a time
  #     request_order: shuffle # reviewers will be chosen in a random order
  #   reviewers:
  #     teams:
  #       - integrathors
  # loki:
  #   conditions:
  #     - "'Loki' in labels"
  #   reviews:
  #     required: 1 # 1 approval from this group are required
  #     request: 2 # 2 reviews requests will be sent at a time
  #     request_order: shuffle # reviewers will be chosen in a random order
  #   reviewers:
  #     teams:
  #       - loki
