/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const mount: typeof import('@vue/test-utils')['mount']
  const shallowMount: typeof import('@vue/test-utils')['shallowMount']
}
