FROM node:lts as builder

WORKDIR '/app'
COPY ./package.json ./
RUN yarn install
COPY . .
RUN git submodule init && git submodule update && cd schulcloud-client && npm install && cd ..
RUN yarn build:nuxt

FROM nginx:alpine
EXPOSE 80
COPY --from=builder /app/dist/nuxt /usr/share/nginx/html/
