FROM node:lts as builder

WORKDIR '/app'
COPY ./package.json ./
RUN yarn install
COPY . .
RUN git submodule init && git submodule update && cd schulcloud-client && npm install && cd ..
RUN yarn build:docs

EXPOSE 3000

CMD yarn dev


FROM nginx:alpine
EXPOSE 80
COPY --from=builder /app/dist/docs /usr/share/nginx/html/
