FROM node:16.11.1 as builder

ENV NUXT_TELEMETRY_DISABLED=1
ARG SC_THEME=default
ENV SC_THEME ${SC_THEME}
EXPOSE 4000

RUN mkdir /app && chown -R node:node /app
WORKDIR '/app'

COPY package.json package-lock.json ./
USER node
RUN npm ci
COPY --chown=node:node . /app/

ENV NODE_ENV=production
RUN ["npm", "run", "build:nuxt"]

CMD [ "./run.sh"]
