FROM node:lts as builder

WORKDIR '/app' 
COPY ./package.json ./
RUN yarn install
COPY . .
RUN git submodule init && git submodule update && cd schulcloud-client && npm install && cd ..
RUN yarn build:storybook

#EXPOSE 6006

CMD yarn storybook --ci



FROM nginx:alpine
EXPOSE 80
COPY --from=builder /app/storybook-static /usr/share/nginx/html/
