
  - name: Configmap
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: configmap.yml.j2
      
  - name: Configmap File
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: configmap-files.yml.j2
      
      