import {
	mdiAccountBoxOutline,
	mdiAccountCircleOutline,
	mdiAccountGroupOutline,
	mdiAccountOffOutline,
	mdiAccountOutline,
	mdiAccountSchoolOutline,
	mdiAlert,
	mdiAlertCircle,
	mdiCalendar,
	mdiCalendarOutline,
	mdiCardAccountDetailsOutline,
	mdiCheck,
	mdiCheckAll,
	mdiCheckboxBlankOutline,
	mdiCheckboxIntermediate,
	mdiCheckboxOutline,
	mdiCheckCircle,
	mdiCheckCircleOutline,
	mdiClose,
	mdiCogOutline,
	mdiDeleteOutline,
	mdiDnsOutline,
	mdiEmailCheckOutline,
	mdiEmailOutline,
	mdiEmailRemoveOutline,
	mdiFileTreeOutline,
	mdiFolder,
	mdiFolderAccount,
	mdiFolderOpenOutline,
	mdiFormatBold,
	mdiFormatItalic,
	mdiFormatListBulleted,
	mdiFormatListChecks,
	mdiFormatListNumbered,
	mdiFormatStrikethrough,
	mdiFormatUnderline,
	mdiHeart,
	mdiHelpCircleOutline,
	mdiImage,
	mdiLaunch,
	mdiLock,
	mdiLockOutline,
	mdiMagnify,
	mdiMenuDown,
	mdiMenuDownOutline,
	mdiMenuSwapOutline,
	mdiMenuUpOutline,
	mdiNewspaperVariantOutline,
	mdiPencilOutline,
	mdiPlus,
	mdiPound,
	mdiPuzzleOutline,
	mdiQrcode,
	mdiRedo,
	mdiSchoolOutline,
	mdiShieldAccountVariantOutline,
	mdiTune,
	mdiUndo,
	mdiViewGridOutline,
} from "@mdi/js";

const materialIcons = {
	"mdi-calendar_outline": mdiCalendarOutline,
	"mdi-check_box_outline_blank": mdiCheckboxBlankOutline,
	"mdi-check_box": mdiCheckboxOutline,
	"mdi-check_circle": mdiCheckCircle,
	"mdi-course_outline": mdiSchoolOutline,
	"mdi-dashboard_outline": mdiViewGridOutline,
	"mdi-done_all": mdiCheckAll,
	"mdi-email_check": mdiEmailCheckOutline,
	"mdi-email_error": mdiEmailRemoveOutline,
	"mdi-error": mdiAlertCircle,
	"mdi-event": mdiCalendar,
	"mdi-favorite": mdiHeart,
	"mdi-file_open_outline": mdiFolderOpenOutline,
	"mdi-folder_shared": mdiFolderAccount,
	"mdi-folder": mdiFolder,
	"mdi-format_bold": mdiFormatBold,
	"mdi-format_italic": mdiFormatItalic,
	"mdi-format_list_bulleted": mdiFormatListBulleted,
	"mdi-format_list_numbered": mdiFormatListNumbered,
	"mdi-format_strikethrough": mdiFormatStrikethrough,
	"mdi-format_underlined": mdiFormatUnderline,
	"mdi-hashtag": mdiPound,
	"mdi-help_area_outline": mdiHelpCircleOutline,
	"mdi-image": mdiImage,
	"mdi-indeterminate_check_box": mdiCheckboxIntermediate,
	"mdi-launch": mdiLaunch,
	"mdi-lock": mdiLock,
	"mdi-news_outline": mdiNewspaperVariantOutline,
	"mdi-puzzle_outline": mdiPuzzleOutline,
	"mdi-redo": mdiRedo,
	"mdi-report_problem": mdiAlert,
	"mdi-setting_outline": mdiCogOutline,
	"mdi-students_outline": mdiAccountSchoolOutline,
	"mdi-success": mdiCheckCircleOutline,
	"mdi-task": mdiFormatListChecks,
	"mdi-undo": mdiUndo,
	mdiAccountBoxOutline,
	mdiAccountCircleOutline,
	mdiAccountGroupOutline,
	mdiAccountOffOutline,
	mdiAccountOutline,
	mdiAccountSchoolOutline,
	mdiAlert,
	mdiCardAccountDetailsOutline,
	mdiCheck,
	mdiCheckAll,
	mdiCheckCircle,
	mdiCheckCircleOutline,
	mdiClose,
	mdiDeleteOutline,
	mdiDnsOutline,
	mdiEmailOutline,
	mdiFileTreeOutline,
	mdiFolder,
	mdiFolderAccount,
	mdiHeart,
	mdiLockOutline,
	mdiMagnify,
	mdiMenuDown,
	mdiMenuDownOutline,
	mdiMenuSwapOutline,
	mdiMenuUpOutline,
	mdiPencilOutline,
	mdiPlus,
	mdiQrcode,
	mdiShieldAccountVariantOutline,
	mdiTune,
};

export default materialIcons;
