/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ColumnResponse } from './column-response';
import { TimestampsResponse } from './timestamps-response';

/**
 * 
 * @export
 * @interface BoardResponse
 */
export interface BoardResponse {
    /**
     * 
     * @type {string}
     * @memberof BoardResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BoardResponse
     */
    title: string;
    /**
     * 
     * @type {Array<ColumnResponse>}
     * @memberof BoardResponse
     */
    columns: Array<ColumnResponse>;
    /**
     * 
     * @type {TimestampsResponse}
     * @memberof BoardResponse
     */
    timestamps: TimestampsResponse;
}


