/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChangeLanguageParams
 */
export interface ChangeLanguageParams {
    /**
     * 
     * @type {string}
     * @memberof ChangeLanguageParams
     */
    language: ChangeLanguageParamsLanguage;
}

/**
    * @export
    * @enum {string}
    */
export enum ChangeLanguageParamsLanguage {
    DE = 'de',
    EN = 'en',
    ES = 'es',
    UA = 'ua'
}



