/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomParameterLocationParams } from './custom-parameter-location-params';
import { CustomParameterScopeTypeParams } from './custom-parameter-scope-type-params';
import { CustomParameterTypeParams } from './custom-parameter-type-params';

/**
 * 
 * @export
 * @interface CustomParameterPostParams
 */
export interface CustomParameterPostParams {
    /**
     * Technical name of the parameter that is send to the tool provider.
     * @type {string}
     * @memberof CustomParameterPostParams
     */
    name: string;
    /**
     * Display name that is shown in the user interface.
     * @type {string}
     * @memberof CustomParameterPostParams
     */
    displayName: string;
    /**
     * Additional description of the parameter in the user interface.
     * @type {string}
     * @memberof CustomParameterPostParams
     */
    description?: string;
    /**
     * Pre-fill value for the parameter. Required for global parameters.
     * @type {string}
     * @memberof CustomParameterPostParams
     */
    defaultValue?: string;
    /**
     * Regular expression to limit user input for this field.
     * @type {string}
     * @memberof CustomParameterPostParams
     */
    regex?: string;
    /**
     * A description for the regex.
     * @type {string}
     * @memberof CustomParameterPostParams
     */
    regexComment?: string;
    /**
     * Scope where the parameter has to be configured.
     * @type {CustomParameterScopeTypeParams}
     * @memberof CustomParameterPostParams
     */
    scope: CustomParameterScopeTypeParams;
    /**
     * Location where the parameter is transmitted in the HTTP request to the tool provider.
     * @type {CustomParameterLocationParams}
     * @memberof CustomParameterPostParams
     */
    location: CustomParameterLocationParams;
    /**
     * Input field type. Auto parameters have to be global and cannot have a defaultValue.
     * @type {CustomParameterTypeParams}
     * @memberof CustomParameterPostParams
     */
    type: CustomParameterTypeParams;
    /**
     * If true, the parameter does not have to be filled out during configuration.
     * @type {boolean}
     * @memberof CustomParameterPostParams
     */
    isOptional: boolean;
    /**
     * If true, the parameter value is not copied to other contexts.
     * @type {boolean}
     * @memberof CustomParameterPostParams
     */
    isProtected: boolean;
}


