/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BasicToolConfigParams } from './basic-tool-config-params';
import { CustomParameterPostParams } from './custom-parameter-post-params';
import { Lti11ToolConfigParams } from './lti11-tool-config-params';
import { Oauth2ToolConfigParams } from './oauth2-tool-config-params';

/**
 * 
 * @export
 * @interface ExternalToolPostParams
 */
export interface ExternalToolPostParams {
    /**
     * 
     * @type {string}
     * @memberof ExternalToolPostParams
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalToolPostParams
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalToolPostParams
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalToolPostParams
     */
    logoUrl?: string;
    /**
     * 
     * @type {BasicToolConfigParams | Lti11ToolConfigParams | Oauth2ToolConfigParams}
     * @memberof ExternalToolPostParams
     */
    config: BasicToolConfigParams | Lti11ToolConfigParams | Oauth2ToolConfigParams;
    /**
     * 
     * @type {Array<CustomParameterPostParams>}
     * @memberof ExternalToolPostParams
     */
    parameters?: Array<CustomParameterPostParams>;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalToolPostParams
     */
    isHidden: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalToolPostParams
     */
    openNewTab: boolean;
}


