/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExternalToolResponse
 */
export interface ExternalToolResponse {
    /**
     * 
     * @type {string}
     * @memberof ExternalToolResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalToolResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalToolResponse
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalToolResponse
     */
    logoUrl?: string;
    /**
     * 
     * @type {object}
     * @memberof ExternalToolResponse
     */
    config: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExternalToolResponse
     */
    parameters: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalToolResponse
     */
    isHidden: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalToolResponse
     */
    openNewTab: boolean;
    /**
     * 
     * @type {number}
     * @memberof ExternalToolResponse
     */
    version: number;
}


