/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Oauth2ToolConfigParams
 */
export interface Oauth2ToolConfigParams {
    /**
     * 
     * @type {string}
     * @memberof Oauth2ToolConfigParams
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2ToolConfigParams
     */
    baseUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2ToolConfigParams
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2ToolConfigParams
     */
    clientSecret?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Oauth2ToolConfigParams
     */
    skipConsent: boolean;
    /**
     * 
     * @type {string}
     * @memberof Oauth2ToolConfigParams
     */
    frontchannelLogoutUri?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2ToolConfigParams
     */
    scope?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Oauth2ToolConfigParams
     */
    redirectUris: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Oauth2ToolConfigParams
     */
    tokenEndpointAuthMethod: string;
}


