/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RichText
 */
export interface RichText {
    /**
     * Content of the rich text element
     * @type {string}
     * @memberof RichText
     */
    content: string;
    /**
     * Input format of the rich text element
     * @type {string}
     * @memberof RichText
     */
    type: RichTextType;
}

/**
    * @export
    * @enum {string}
    */
export enum RichTextType {
    PLAINTEXT = 'plaintext',
    RICHTEXT = 'richtext',
    INLINE = 'inline',
    RICHTEXT_CK4 = 'richtext_ck4',
    RICHTEXT_CK5 = 'richtext_ck5',
    RICHTEXT_CK5_INLINE = 'richtext_ck5_inline'
}



