/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShareTokenPayloadResponse
 */
export interface ShareTokenPayloadResponse {
    /**
     * 
     * @type {string}
     * @memberof ShareTokenPayloadResponse
     */
    parentType: ShareTokenPayloadResponseParentType;
    /**
     * 
     * @type {string}
     * @memberof ShareTokenPayloadResponse
     */
    parentId: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ShareTokenPayloadResponseParentType {
    COURSES = 'courses',
    TASKS = 'tasks',
    LESSONS = 'lessons'
}



