/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BoardElementResponse } from './board-element-response';

/**
 * 
 * @export
 * @interface SingleColumnBoardResponse
 */
export interface SingleColumnBoardResponse {
    /**
     * The id of the room this board belongs to
     * @type {string}
     * @memberof SingleColumnBoardResponse
     */
    roomId: string;
    /**
     * Title of the Board
     * @type {string}
     * @memberof SingleColumnBoardResponse
     */
    title: string;
    /**
     * Color of the Board
     * @type {string}
     * @memberof SingleColumnBoardResponse
     */
    displayColor: string;
    /**
     * Array of board specific tasks or lessons with matching type property
     * @type {Array<BoardElementResponse>}
     * @memberof SingleColumnBoardResponse
     */
    elements: Array<BoardElementResponse>;
}


