/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskCreateParams
 */
export interface TaskCreateParams {
    /**
     * The id of an course object.
     * @type {string}
     * @memberof TaskCreateParams
     */
    courseId?: string;
    /**
     * List of users ids, which belong to course. This restricts access to the task.
     * @type {Array<string>}
     * @memberof TaskCreateParams
     */
    usersIds?: Array<string> | null;
    /**
     * The id of an lesson object.
     * @type {string}
     * @memberof TaskCreateParams
     */
    lessonId?: string;
    /**
     * The title of the task
     * @type {string}
     * @memberof TaskCreateParams
     */
    name: string;
    /**
     * The description of the task
     * @type {string}
     * @memberof TaskCreateParams
     */
    description?: string;
    /**
     * Date since the task is published
     * @type {string}
     * @memberof TaskCreateParams
     */
    availableDate?: string;
    /**
     * Date until the task submissions can be sent
     * @type {string}
     * @memberof TaskCreateParams
     */
    dueDate?: string;
}


