/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TextElementContent } from './text-element-content';
import { TimestampsResponse } from './timestamps-response';

/**
 * 
 * @export
 * @interface TextElementResponse
 */
export interface TextElementResponse {
    /**
     * 
     * @type {string}
     * @memberof TextElementResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TextElementResponse
     */
    type: TextElementResponseType;
    /**
     * 
     * @type {TextElementContent}
     * @memberof TextElementResponse
     */
    content: TextElementContent;
    /**
     * 
     * @type {TimestampsResponse}
     * @memberof TextElementResponse
     */
    timestamps: TimestampsResponse;
}

/**
    * @export
    * @enum {string}
    */
export enum TextElementResponseType {
    TEXT = 'text'
}



