galaxy_info:
  role_name: nuxt-client-ldap
  author: Schul-Cloud Verbund
  description: ldap role for the nuxt-client
  company: Schul-Cloud Verbund
  license: license (AGPLv3)
  min_ansible_version: 2.8
  galaxy_tags: []
dependencies: []
