// Whitelisted Vue routes
// everything else will be forwarded to the legacy client
// using the ./proxy.js serverMiddleware

const mongoId = "[a-z0-9]{24}";
const h5pId = "[a-z0-9]+";

const vueRoutes = [
	`^/administration/?$`,
	`^/administration/groups/classes/?$`,
	`^/administration/groups/classes/${mongoId}/?$`,
	`^/administration/ldap/activate/?$`,
	`^/administration/ldap/config/?$`,
	`^/administration/migration/?$`,
	`^/administration/rooms/manage/?$`,
	`^/administration/rooms/manage/${mongoId}?$`,
	`^/administration/rooms/new/?$`,
	`^/administration/school-settings/?$`,
	`^/administration/school-settings/provisioning-options/?$`,
	`^/administration/school-settings/tool-configuration/?$`,
	`^/administration/school-settings/tool-configuration/${mongoId}/?$`,
	`^/administration/students/?$`,
	`^/administration/students/consent/?$`,
	`^/administration/students/new/?$`,
	`^/administration/teachers/?$`,
	`^/administration/teachers/new/?$`,
	`^/boards(/.*)?$`,
	`^/collabora(/.*)?$`,
	`^/dashboard/?$`,
	`^/error/?$`,
	`^/favicon.png$`,
	`^/folder(/.*)?$`,
	`^/h5p/editor/?$`,
	`^/h5p/editor/${h5pId}/?$`,
	`^/h5p/player(/.*)?$`,
	`^/imprint/?$`,
	`^/licenses/?$`,
	`^/media-shelf/?$`,
	`^/media-shelf/fwu-media/?$`,
	`^/migration/?$`,
	`^/migration/error/?$`,
	`^/migration/success/?$`,
	`^/news/${mongoId}/?$`,
	`^/news/${mongoId}/edit/?$`,
	`^/news/new/?$`,
	`^/poc-files/?$`,
	`^/registration-external-members/?$`,
	`^/rooms-overview/?$`,
	`^/rooms/?$`,
	`^/rooms/${mongoId}/?$`,
	`^/rooms/${mongoId}/board/?$`,
	`^/rooms/${mongoId}/edit/?$`,
	`^/rooms/${mongoId}/members/?$`,
	`^/rooms/courses-list/?$`,
	`^/rooms/courses-overview/?$`,
	`^/rooms/invitation-link(/.*)?$`,
	`^/rooms/new/?$`,
	`^/runtime.config.json`,
	`^/system/security`,
	`^/tasks/?$`,
	`^/tools/context/tool-configuration/?$`,
	`^/tools/context/tool-configuration/${mongoId}/?$`,
	`^/@`,
	`^/_nuxt/*`,
	`^/node_modules/`,
	`^/src/`,
];

export const isVueClient = (path: string) => vueRoutes.some((regex) => new RegExp(regex).exec(path));
