FROM node:lts as builder

WORKDIR '/app'
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build:storybook > /dev/null 2>&1

FROM nginx:alpine
EXPOSE 80
COPY --from=builder /app/dist/storybook /usr/share/nginx/html/
