FROM node:lts as builder

WORKDIR '/app'
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci
COPY . /app

EXPOSE 4000
# RUN ["chmod", "550", "./startup.sh"]
# CMD [ "./startup.sh"]
RUN npm run build:nuxt
CMD npm run start
