FROM node:lts as builder
RUN apt-get update && \
    apt-get install git

WORKDIR '/app'
COPY ./package.json ./
COPY ./yarn.lock ./
RUN npm i -g gulp
RUN yarn
COPY . /app

# Legacy Client
RUN git submodule init
RUN git submodule update --remote
WORKDIR '/app/src/legacy-client'
RUN npm i
RUN gulp
WORKDIR '/app'
RUN yarn build:nuxt

CMD [ "./startup.sh"]
