FROM node:lts as builder

# Algolia search
ARG ALGOLIA_API_KEY
ENV ALGOLIA_API_KEY=$ALGOLIA_API_KEY
ARG ALGOLIA_NAME
ENV ALGOLIA_NAME=$ALGOLIA_NAME

WORKDIR '/app'
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm i
COPY . .
RUN npm run build:docs

FROM nginx:alpine
EXPOSE 80
COPY --from=builder /app/dist/docs /usr/share/nginx/html/
