FROM node:lts as builder

WORKDIR '/app'
COPY ./package.json ./
RUN yarn install
COPY . /app
RUN git submodule init && git submodule update
RUN yarn build:nuxt

FROM nginx:alpine
EXPOSE 80

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=80

CMD [ "yarn", "start" ]