import { User } from "@/store/types/auth";
import { School } from "@/store/types/schools";

export const mockUser: User = {
	_id: "",
	__v: 0,
	firstName: "",
	lastName: "",
	email: "",
	updatedAt: "",
	birthday: "",
	createdAt: "",
	preferences: {},
	schoolId: "",
	roles: [
		{
			_id: "",
			name: "test-role",
			updatedAt: "",
			createdAt: "",
			roles: [],
			permissions: [],
			__v: 2,
			displayName: "test-display-name",
			id: "",
		},
	],
	emailSearchValues: [],
	firstNameSearchValues: [],
	lastNameSearchValues: [],
	consent: {
		userConsent: {
			form: "",
			privacyConsent: true,
			termsOfUseConsent: true,
			dateOfPrivacyConsent: "",
			dateOfTermsOfUseConsent: "",
		},
	},
	forcePasswordChange: false,
	language: "",
	fullName: "",
	id: "",
	avatarInitials: "",
	avatarBackgroundColor: "",
	age: 44,
	displayName: "",
	permissions: ["test-permission"],
	accountId: "",
	schoolName: "",
	externallyManaged: false,
};

export const mockSchool: School = {
	id: "mockSchoolId",
	name: "",
	logo_name: "",
	fileStorageType: "",
	federalState: {
		id: "",
		counties: [],
		name: "",
		abbreviation: "",
		logoUrl: "",
		__v: 0,
	},
	county: {
		antaresKey: "",
		id: "",
		countyId: "",
		name: "",
	},
	systems: [],
	updatedAt: "",
	createdAt: "",
	__v: 0,
	currentYear: {
		id: "",
		name: "",
		startDate: "",
		endDate: "",
		__v: 0,
	},
	purpose: "",
	features: {
		rocketChat: false,
		videoconference: false,
		studentVisibility: false,
		ldapUniventionMigrationSchool: false,
		showOutdatedUsers: false,
		enableLdapSyncDuringMigration: false,
		isTeamCreationByStudentsEnabled: false,
		nextcloud: false,
		oauthProvisioningEnabled: false,
	},
	permissions: {},
	inMaintenance: false,
	inUserMigration: false,
	documentBaseDir: "",
	isExternal: false,
	years: {},
};
