export const INJECT_SPEED_DIAL_ORIENTATION = Symbol("INJECT_SPEED_DIAL_ORIENTATION");

export const INJECT_SPEED_DIAL_DIRECTION = Symbol("INJECT_SPEED_DIAL_DIRECTION");

export const INJECT_SPEED_DIAL_ACTION_CLICKED = Symbol("INJECT_SPEED_DIAL_ACTION_CLICKED");
