import { useI18nGlobal } from "@/plugins/i18n";
import { useAppStore } from "@data-app";
import { createSharedComposable } from "@vueuse/core";
import dayjs from "dayjs";
import customParseFormat from "dayjs/plugin/customParseFormat";
import relativeTime from "dayjs/plugin/relativeTime";
import timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";
import { storeToRefs } from "pinia";
import { computed } from "vue";

dayjs.extend(customParseFormat);
dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.extend(relativeTime);

const LOCALIZED_DATE_PLACEHOLDER_TOKENS: { [localeCode: string]: { day: string; month: string; year: string } } = {
	de: { day: "TT", month: "MM", year: "JJJJ" },
	en: { day: "DD", month: "MM", year: "YYYY" },
	es: { day: "DD", month: "MM", year: "AAAA" },
	uk: { day: "ДД", month: "ММ", year: "РРРР" },
};

const DAYJS_FORMAT_TOKENS: { [localeCode: string]: string } = {
	de: "DD.MM.YYYY",
	en: "DD/MM/YYYY",
	es: "DD/MM/YYYY",
	uk: "DD.MM.YYYY",
};

const DATE_REGEX_PATTERNS: Record<string, string> = {
	D: "(0[1-9]|[12]\\d|3[01])",
	M: "(0[1-9]|1[0-2])",
	Y: "\\d{4}",
};

export const useLocalizedDateTime = createSharedComposable(() => {
	const locale = storeToRefs(useAppStore()).locale;
	// The default returned when using Intl.DateTimeFormat with "en" is "en-US", whose format is not preferred here.
	const localeRegion = computed(() => (locale.value === "en" ? "en-GB" : locale.value));

	const refFormatted = computed(() =>
		new Intl.DateTimeFormat(localeRegion.value, {
			day: "2-digit",
			month: "2-digit",
			year: "numeric",
		}).format(new Date(2000, 2, 15))
	);

	const datePlaceHolder = computed(() => {
		const tokens = LOCALIZED_DATE_PLACEHOLDER_TOKENS[locale.value];
		return refFormatted.value.replace("2000", tokens.year).replace("15", tokens.day).replace("03", tokens.month);
	});

	// The mask is generated by replacing all non-delimiter characters with "#"
	const dateMask = computed(() => datePlaceHolder.value.replace(/[^.\s/:,-]/gu, "#"));

	const dateRegex = computed(() => {
		const delimiter = refFormatted.value.replace(/\d/g, "")[0];
		const escapedDelimiter = delimiter.replace(".", "\\.");
		const order = refFormatted.value.replace("2000", "Y").replace("15", "D").replace("03", "M").split(/\W/);

		const pattern = order.map((k) => DATE_REGEX_PATTERNS[k]).join(escapedDelimiter);
		return new RegExp(`^${pattern}$`);
	});
	const timeRegex = /^([01]\d|2[0-3]):[0-5]\d$/;
	const timePlaceHolder = "HH:mm";
	const timeMask = "##:##";

	return {
		datePlaceHolder,
		dateMask,
		dateRegex,
		timePlaceHolder,
		timeMask,
		timeRegex,
		locale,
	};
});

export const useDateConversion = () => {
	const { locale } = useLocalizedDateTime();
	const { d } = useI18nGlobal();

	const dayjsFormat = computed(() => DAYJS_FORMAT_TOKENS[locale.value] ?? "DD/MM/YYYY");

	/**
	 * Parse a date from local representation to date object.
	 *
	 * @param dateString - The date string in local representation (e.g. "31.12.2024" for German locale)
	 */
	const convertDateStringToDate = (dateString: string | undefined) => {
		const parsed = dayjs(dateString, dayjsFormat.value);
		return parsed.isValid() ? parsed.toDate() : undefined;
	};

	/**
	 * Parse a date from local representation to an iso date string. It's not used for date and time representation.
	 *
	 * @param dateString - The date string in local representation (e.g. "31.12.2024" for German locale)
	 */
	const convertDateStringToIso = (dateString: string | undefined) =>
		dateString ? dayjs(dateString, dayjsFormat.value).format("YYYY-MM-DD") : undefined;

	/**
	 * Converts an ISO date string to a localized date string based on the current locale.
	 *
	 * @param isoString - The ISO date string to convert (e.g. "2024-12-31T00:00:00.000Z")
	 */
	const convertIsoToDateString = (isoString: string | undefined) => (isoString ? d(isoString, "date") : undefined);

	/**
	 * Parse a date from DB representation (DD.MM.YYYY) to an iso date string. Deprecated - in DB there should only be ISO date strings, so this is only needed for legacy data and should not be used for new code.
	 * @deprecated - Use convertIsoToDateString() if possible.
	 *
	 * @param dbDateString - The date string in DB format (e.g. "01.03.2022")
	 */
	const convertDbGermanDateStringToDateString = (dbDateString: string | undefined) => {
		const iso = dayjs(dbDateString, "DD.MM.YYYY").toISOString();
		return convertIsoToDateString(iso);
	};

	/**
	 * Converts a date-only string (YYYY-MM-DD) to an end-of-day ISO timestamp.
	 *
	 * @param dateString - The date string in YYYY-MM-DD format (e.g. "2026-03-04")
	 */
	const convertDateToEndOfDayIso = (dateString: string | undefined) => {
		if (!dateString) return undefined;
		return dayjs(dateString).endOf("day").toISOString();
	};

	return {
		convertDbGermanDateStringToDateString,
		convertDateStringToIso,
		convertDateStringToDate,
		convertIsoToDateString,
		convertDateToEndOfDayIso,
	};
};
