import { useAppStore } from "@data-app";
import { createSharedComposable } from "@vueuse/core";
import { storeToRefs } from "pinia";
import { computed } from "vue";

const LOCALIZED_DATE_PLACEHOLDER_TOKENS: { [localeCode: string]: { day: string; month: string; year: string } } = {
	de: { day: "TT", month: "MM", year: "JJJJ" },
	en: { day: "DD", month: "MM", year: "YYYY" },
	es: { day: "DD", month: "MM", year: "AAAA" },
	uk: { day: "ДД", month: "ММ", year: "РРРР" },
};

const DATE_REGEX_PATTERNS: Record<string, string> = {
	D: "(0[1-9]|[12]\\d|3[01])",
	M: "(0[1-9]|1[0-2])",
	Y: "\\d{4}",
};

export const useLocalizedDateTime = createSharedComposable(() => {
	const locale = storeToRefs(useAppStore()).locale;
	// The default returned when using Intl.DateTimeFormat with "en" is "en-US", whose format is not preferred here.
	const localeRegion = computed(() => (locale.value === "en" ? "en-GB" : locale.value));

	const refFormatted = computed(() =>
		new Intl.DateTimeFormat(localeRegion.value, {
			day: "2-digit",
			month: "2-digit",
			year: "numeric",
		}).format(new Date(2000, 2, 15))
	);

	const datePlaceHolder = computed(() => {
		const tokens = LOCALIZED_DATE_PLACEHOLDER_TOKENS[locale.value];
		return refFormatted.value.replace("2000", tokens.year).replace("15", tokens.day).replace("03", tokens.month);
	});

	// The mask is generated by replacing all non-delimiter characters with "#"
	const dateMask = computed(() => datePlaceHolder.value.replace(/[^.\s/:,-]/gu, "#"));

	const dateRegex = computed(() => {
		const delimiter = refFormatted.value.replace(/\d/g, "")[0];
		const escapedDelimiter = delimiter.replace(".", "\\.");
		const order = refFormatted.value.replace("2000", "Y").replace("15", "D").replace("03", "M").split(/\W/);

		const pattern = order.map((k) => DATE_REGEX_PATTERNS[k]).join(escapedDelimiter);
		return new RegExp(`^${pattern}$`);
	});

	const timePlaceHolder = "HH:mm";
	const timeMask = "##:##";

	return { datePlaceHolder, dateMask, dateRegex, timePlaceHolder, timeMask };
});
