/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/account-api';
export * from './api/authentication-api';
export * from './api/boards-api';
export * from './api/cards-api';
export * from './api/collaborative-storage-api';
export * from './api/courses-api';
export * from './api/dashboard-api';
export * from './api/default-api';
export * from './api/lesson-api';
export * from './api/news-api';
export * from './api/oauth2-api';
export * from './api/rooms-api';
export * from './api/ssoapi';
export * from './api/school-api';
export * from './api/share-token-api';
export * from './api/submission-api';
export * from './api/systems-api';
export * from './api/task-api';
export * from './api/tool-api';
export * from './api/user-api';
export * from './api/user-import-api';
export * from './api/user-migration-api';
export * from './api/video-conference-api';

