export enum BoardMenuScope {
	CARD = "card",
	COLUMN = "column",
	BOARD = "board",
	COLLABORATIVE_TEXT_EDITOR_ELEMENT = "collaborativeTextEditorElement",
	DRAWING_ELEMENT = "drawingElement",
	EXTERNAL_TOOL_ELEMENT = "externalToolElement",
	FILE_ELEMENT = "fileElement",
	LINK_ELEMENT = "linkElement",
	SUBMISSION_ELEMENT = "submissionElement",
	DELETED_ELEMENT = "deletedElement",
	MEDIA_EXTERNAL_TOOL_ELEMENT = "mediaExternalToolElement",
	VIDEO_CONFERENCE_ELEMENT = "videoConferenceElement",
	AUDIO_RECORD_ELEMENT = "audioRecordEllement",
}
