/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CopyFileResponse } from './copy-file-response';

/**
 * 
 * @export
 * @interface CopyFileListResponse
 */
export interface CopyFileListResponse {
    /**
     * The items for the current page.
     * @type {Array<CopyFileResponse>}
     * @memberof CopyFileListResponse
     */
    data: Array<CopyFileResponse>;
    /**
     * The total amount of items.
     * @type {number}
     * @memberof CopyFileListResponse
     */
    total: number;
    /**
     * The amount of items skipped from the start.
     * @type {number}
     * @memberof CopyFileListResponse
     */
    skip: number;
    /**
     * The page size of the response.
     * @type {number}
     * @memberof CopyFileListResponse
     */
    limit: number;
}


