/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software File Storage API
 * This is the API documentation for the Schulcloud-Verbund-Software File Storage API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EditorMode } from './editor-mode';

/**
 * 
 * @export
 * @interface DiscoveryAccessUrlParams
 */
export interface DiscoveryAccessUrlParams {
    /**
     * 
     * @type {string}
     * @memberof DiscoveryAccessUrlParams
     */
    fileRecordId: string;
    /**
     * 
     * @type {EditorMode}
     * @memberof DiscoveryAccessUrlParams
     */
    editorMode: EditorMode;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryAccessUrlParams
     */
    userDisplayName: string;
}


