/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileRecordParams
 */
export interface FileRecordParams {
    /**
     * 
     * @type {string}
     * @memberof FileRecordParams
     */
    schoolId: string;
    /**
     * 
     * @type {string}
     * @memberof FileRecordParams
     */
    parentId: string;
    /**
     * 
     * @type {string}
     * @memberof FileRecordParams
     */
    parentType: FileRecordParamsParentType;
}

/**
    * @export
    * @enum {string}
    */
export enum FileRecordParamsParentType {
    USERS = 'users',
    SCHOOLS = 'schools',
    COURSES = 'courses',
    TASKS = 'tasks',
    LESSONS = 'lessons',
    SUBMISSIONS = 'submissions',
    BOARDNODES = 'boardnodes'
}



