/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software File Storage API
 * This is the API documentation for the Schulcloud-Verbund-Software File Storage API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FileRecordParentType } from './file-record-parent-type';
import { StorageLocation } from './storage-location';

/**
 * 
 * @export
 * @interface FileRecordParams
 */
export interface FileRecordParams {
    /**
     * 
     * @type {string}
     * @memberof FileRecordParams
     */
    storageLocationId: string;
    /**
     * 
     * @type {StorageLocation}
     * @memberof FileRecordParams
     */
    storageLocation: StorageLocation;
    /**
     * 
     * @type {string}
     * @memberof FileRecordParams
     */
    parentId: string;
    /**
     * 
     * @type {FileRecordParentType}
     * @memberof FileRecordParams
     */
    parentType: FileRecordParentType;
}


