/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software File Storage API
 * This is the API documentation for the Schulcloud-Verbund-Software File Storage API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ParentStatisticResponse
 */
export interface ParentStatisticResponse {
    /**
     * The number of files for the parent entity.
     * @type {number}
     * @memberof ParentStatisticResponse
     */
    fileCount: number;
    /**
     * The total size in bytes of all files for the parent entity.
     * @type {number}
     * @memberof ParentStatisticResponse
     */
    totalSizeInBytes: number;
}


