/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software File Storage API
 * This is the API documentation for the Schulcloud-Verbund-Software File Storage API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WopiCheckFileInfoResponse
 */
export interface WopiCheckFileInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof WopiCheckFileInfoResponse
     */
    BaseFileName: string;
    /**
     * 
     * @type {number}
     * @memberof WopiCheckFileInfoResponse
     */
    Size: number;
    /**
     * 
     * @type {string}
     * @memberof WopiCheckFileInfoResponse
     */
    OwnerID: string;
    /**
     * 
     * @type {string}
     * @memberof WopiCheckFileInfoResponse
     */
    UserId: string;
    /**
     * 
     * @type {boolean}
     * @memberof WopiCheckFileInfoResponse
     */
    UserCanWrite: boolean;
    /**
     * 
     * @type {string}
     * @memberof WopiCheckFileInfoResponse
     */
    UserFriendlyName: string;
}


