---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build_and_push_nuxt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tennens: [default, brb, demo, int, n21, open, thr ]
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta Service Name
        id: docker_meta_img
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.tennens }}
          tags: |
            type=ref,event=branch,enable=false,priority=600
            type=sha,enable=true,priority=600,prefix=

      - name: Docker meta Service Name for docker hub
        id: docker_meta_img_hub
        uses: docker/metadata-action@v3
        with:
          images: schulcloud/schulcloud-nuxt-client-${{ matrix.tennens }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            SC_THEME=${{ matrix.tennens }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img_hub.outputs.labels }}
