name: Test screenshot

on: [push]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm ci
        # apt-get is to fix issue: https://github.com/puppeteer/puppeteer/issues/5704#issuecomment-618372226
        run: |
          sudo apt-get update && sudo apt-get install -y libgbm1
          npm ci --prefer-offline --no-audit
      - name: build storybook
        run: "npm run build:storybook"
      - name: npm run test:screenshot
        run: npm run test:screenshot:ci
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: screenshot-diff
          path: tests/screenshot/__image_snapshots__/__diff_output__
      - name: failure hint
        if: failure()
        run: echo "if you want to update the screenshots, comment \"@schul-cloud-bot update screenshots\" on this PR."