name: Test e2e

on: [push]

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["run-e2e-tests"]'
      - uses: actions/checkout@v2
      - name: run git change
        if: ${{ steps.check_pr_labels.outputs.result }}
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
      - name: execute tests
        if: ${{ steps.check_pr_labels.outputs.result }}
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          MY_DOCKER_PASSWORD: ${{ secrets.MY_DOCKER_PASSWORD }}
        run: curl "https://raw.githubusercontent.com/hpi-schul-cloud/end-to-end-tests/develop/scripts/ci/fetch.github.sh" | bash
      - uses: actions/upload-artifact@v1
        name: upload results
        if: ${{ steps.check_pr_labels.outputs.result }}
        with:
          name: report
          path: end-to-end-tests/reports
  end-to-end-hint:
    if: "!contains( github.event.pull_request.labels.*.name, 'run-e2e-tests')"
    runs-on: ubuntu-latest
    steps:
      - name: run e2e hint
        run: echo "if you want to run e2e tests, add label \"run-e2e-tests\" on this PR."
  # build:
  #   strategy:
  #     matrix:
  #       theme: [default, brb, n21, open, thr, int]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: npm ci
  #       run: npm ci --prefer-offline
  #     - name: npm run build:nuxt
  #       run: npm run build:nuxt
  #       env:
  #         SC_THEME: ${{ matrix.theme }}
