name: Test e2e

on:
  pull_request:

jobs:
  end-to-end-tests:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run git change
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
      - name: execute tests
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          MY_DOCKER_PASSWORD: ${{ secrets.MY_DOCKER_PASSWORD }}
        run: curl "https://raw.githubusercontent.com/hpi-schul-cloud/end-to-end-tests/develop/scripts/ci/fetch.github.sh" | bash
      - uses: actions/upload-artifact@v1
        name: upload results
        if: always()
        with:
          name: report
          path: end-to-end-tests/reports
  # build:
  #   strategy:
  #     matrix:
  #       theme: [default, brb, n21, open, thr, int]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: npm ci
  #       run: npm ci --prefer-offline
  #     - name: npm run build:nuxt
  #       run: npm run build:nuxt
  #       env:
  #         SC_THEME: ${{ matrix.theme }}
